-- =====================================================================
-- WES HOUSE ENGLISH SCHOOL — SUPABASE SCHEMA UPDATE
-- Ejecutar en el SQL Editor de Supabase
-- =====================================================================

-- 1. CREACIÓN DE NUEVAS TABLAS DE MÓDULOS FALTANTES
-- ---------------------------------------------------------------------

-- MÓDULO 6: SISTEMA DE NOTIFICACIONES INTERNAS
CREATE TABLE IF NOT EXISTS public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    type TEXT DEFAULT 'info', -- 'success', 'warning', 'danger', 'info'
    read BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Asegurar columnas si la tabla ya existía
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'info';
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS read BOOLEAN DEFAULT false;
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS target TEXT DEFAULT 'all';
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS views INTEGER DEFAULT 0;


-- MÓDULO 8: RESERVAS DE CLASES DE CONVERSACIÓN
CREATE TABLE IF NOT EXISTS public.conversation_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    time_start TIME NOT NULL,
    time_end TIME NOT NULL,
    max_capacity INTEGER DEFAULT 5,
    current_capacity INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_id BIGINT REFERENCES public.conversation_slots(id) ON DELETE CASCADE,
    student_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT unique_booking UNIQUE (slot_id, student_id)
);

-- MÓDULO 10: LISTA DE ESPERA / INSCRIPCIÓN PÚBLICA
CREATE TABLE IF NOT EXISTS public.waitlist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    phone TEXT,
    level_requested TEXT DEFAULT 'A1',
    status TEXT DEFAULT 'pending', -- 'pending', 'approved', 'rejected'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- 2. HABILITACIÓN DE RLS (ROW LEVEL SECURITY)
-- ---------------------------------------------------------------------
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversation_slots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.grades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.waitlist ENABLE ROW LEVEL SECURITY;


-- 3. FUNCIONES AUXILIARES DE SEGURIDAD (SECURITY DEFINER)
-- ---------------------------------------------------------------------

-- Helper para obtener el rol del usuario conectado desde public.users
CREATE OR REPLACE FUNCTION public.get_my_role()
RETURNS text AS $$
DECLARE
    v_role text;
BEGIN
    SELECT role INTO v_role 
    FROM public.users 
    WHERE email = auth.jwt() ->> 'email';
    
    RETURN COALESCE(v_role, 'student');
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- 4. POLÍTICAS DE ACCESO RLS POR TABLA
-- ---------------------------------------------------------------------

-- POLÍTICAS: public.users
CREATE POLICY "users_admin_all" ON public.users FOR ALL USING (public.get_my_role() = 'admin');
CREATE POLICY "users_teacher_select" ON public.users FOR SELECT USING (public.get_my_role() = 'teacher');
CREATE POLICY "users_student_self" ON public.users FOR SELECT USING (email = auth.jwt() ->> 'email');

-- POLÍTICAS: public.courses
CREATE POLICY "courses_admin_all" ON public.courses FOR ALL USING (public.get_my_role() = 'admin');
CREATE POLICY "courses_teacher_select" ON public.courses FOR SELECT USING (public.get_my_role() = 'teacher' AND teacher_id IN (SELECT id FROM public.users WHERE email = auth.jwt() ->> 'email'));
CREATE POLICY "courses_student_select" ON public.courses FOR SELECT USING (public.get_my_role() = 'student' AND id IN (SELECT course_id FROM public.users WHERE email = auth.jwt() ->> 'email'));

-- POLÍTICAS: public.attendance
CREATE POLICY "attendance_admin_all" ON public.attendance FOR ALL USING (public.get_my_role() = 'admin');
CREATE POLICY "attendance_teacher_all" ON public.attendance FOR ALL USING (public.get_my_role() = 'teacher');
CREATE POLICY "attendance_student_select" ON public.attendance FOR SELECT USING (student_id IN (SELECT id FROM public.users WHERE email = auth.jwt() ->> 'email'));

-- POLÍTICAS: public.payments
CREATE POLICY "payments_admin_all" ON public.payments FOR ALL USING (public.get_my_role() = 'admin');
CREATE POLICY "payments_student_select" ON public.payments FOR SELECT USING (student_id IN (SELECT id FROM public.users WHERE email = auth.jwt() ->> 'email'));

-- POLÍTICAS: public.materials
CREATE POLICY "materials_admin_teacher_all" ON public.materials FOR ALL USING (public.get_my_role() IN ('admin', 'teacher'));
CREATE POLICY "materials_student_select" ON public.materials FOR SELECT USING (
    course_id IN (SELECT course_id FROM public.users WHERE email = auth.jwt() ->> 'email')
);

-- POLÍTICAS: public.notifications
CREATE POLICY "notifications_select" ON public.notifications FOR SELECT USING (
    user_id = (SELECT id FROM public.users WHERE email = auth.jwt() ->> 'email') OR 
    user_id IS NULL OR 
    public.get_my_role() = 'admin'
);

CREATE POLICY "notifications_student_update" ON public.notifications FOR UPDATE USING (
    user_id = (SELECT id FROM public.users WHERE email = auth.jwt() ->> 'email')
);

CREATE POLICY "notifications_admin_all" ON public.notifications FOR ALL USING (
    public.get_my_role() = 'admin'
);

-- POLÍTICAS: public.grades
CREATE POLICY "grades_admin_all" ON public.grades FOR ALL USING (public.get_my_role() = 'admin');
CREATE POLICY "grades_teacher_all" ON public.grades FOR ALL USING (public.get_my_role() = 'teacher');
CREATE POLICY "grades_student_select" ON public.grades FOR SELECT USING (student_id IN (SELECT id FROM public.users WHERE email = auth.jwt() ->> 'email'));

-- POLÍTICAS: public.logs
CREATE POLICY "logs_admin_all" ON public.logs FOR ALL USING (public.get_my_role() = 'admin');

-- POLÍTICAS: public.waitlist
CREATE POLICY "waitlist_public_insert" ON public.waitlist FOR INSERT WITH CHECK (true);
CREATE POLICY "waitlist_admin_all" ON public.waitlist FOR ALL USING (public.get_my_role() = 'admin');


-- 5. TRIGGERS DE AUTOMATIZACIÓN
-- ---------------------------------------------------------------------

-- AUTOMATIZACIÓN 17: Alerta automática de asistencia baja (< 75%)
CREATE OR REPLACE FUNCTION public.check_low_attendance()
RETURNS TRIGGER AS $$
DECLARE
    v_total_clases integer;
    v_asistencias integer;
    v_porcentaje numeric;
    v_student_email text;
    v_student_name text;
BEGIN
    SELECT count(*) INTO v_total_clases 
    FROM public.attendance 
    WHERE student_id = NEW.student_id AND course_id = NEW.course_id;

    SELECT count(*) INTO v_asistencias 
    FROM public.attendance 
    WHERE student_id = NEW.student_id AND course_id = NEW.course_id AND status = 'Presente';

    IF v_total_clases >= 5 THEN -- Analizar tras mínimo 5 clases registradas
        v_porcentaje := (v_asistencias::numeric / v_total_clases::numeric) * 100;
        
        IF v_porcentaje < 75.0 THEN
            SELECT email, name INTO v_student_email, v_student_name FROM public.users WHERE id = NEW.student_id;
            
            -- Insertar notificación automática para el alumno/tutor
            INSERT INTO public.notifications (user_id, title, message, type)
            VALUES (
                NEW.student_id,
                'Alerta de Asistencia Baja',
                'Tu asistencia actual en este curso es de ' || round(v_porcentaje, 1) || '%, lo cual está por debajo del 75% mínimo requerido.',
                'danger'
            );
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER tr_attendance_analysis
AFTER INSERT OR UPDATE ON public.attendance
FOR EACH ROW EXECUTE FUNCTION public.check_low_attendance();


-- AUTOMATIZACIÓN 19: Promoción automática de nivel (A1->A2->...)
CREATE OR REPLACE FUNCTION public.promote_student_level()
RETURNS TRIGGER AS $$
DECLARE
    v_current_level text;
    v_next_level text;
BEGIN
    -- Si es examen final y la nota es aprobatoria (>= 7.0)
    IF NEW.exam_type = 'final_exam' AND NEW.score >= 7.0 THEN
        SELECT level INTO v_current_level FROM public.users WHERE id = NEW.student_id;

        v_next_level := CASE v_current_level
            WHEN 'A1' THEN 'A2'
            WHEN 'A2' THEN 'B1'
            WHEN 'B1' THEN 'B2'
            WHEN 'B2' THEN 'C1'
            WHEN 'C1' THEN 'C2'
            ELSE v_current_level
        END;

        IF v_next_level <> v_current_level THEN
            UPDATE public.users SET level = v_next_level WHERE id = NEW.student_id;
            
            -- Notificar al alumno
            INSERT INTO public.notifications (user_id, title, message, type)
            VALUES (
                NEW.student_id,
                '¡Felicitaciones! Promoción de Nivel',
                'Has aprobado tu examen final y has sido promovido al nivel ' || v_next_level || '.',
                'success'
            );

            -- Log de auditoría
            INSERT INTO public.logs (user_id, action, table_name, details)
            VALUES (
                NEW.student_id,
                'LEVEL_PROMOTION',
                'users',
                json_build_object('from', v_current_level, 'to', v_next_level)::text
            );
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER tr_grades_promotion
AFTER INSERT OR UPDATE ON public.grades
FOR EACH ROW EXECUTE FUNCTION public.promote_student_level();


-- 6. TAREAS CRON PROGRAMADAS (pg_cron)
-- ---------------------------------------------------------------------

-- Crear tabla auxiliar de configuración para habilitar pg_cron si está disponible
CREATE EXTENSION IF NOT EXISTS pg_cron;

-- Job 18: Recordatorio de pagos pendientes 5 días antes de vencer (Corre todos los días a las 9am)
SELECT cron.schedule(
    'daily-payment-reminder',
    '0 9 * * *',
    $$
    INSERT INTO public.notifications (user_id, title, message, type)
    SELECT 
        student_id, 
        'Recordatorio de Pago de Cuota', 
        'Tu cuota mensual de $' || amount || ' vencerá pronto (el ' || date || '). Evita atrasos.',
        'warning'
    FROM public.payments 
    WHERE status = 'Pendiente' AND date = (CURRENT_DATE + INTERVAL '5 days');
    $$
);
