// Crear tablas académicas via Supabase Management API
// Esta API permite ejecutar SQL arbitrario como admin

const fetch = (...args) => import('node-fetch').then(({default: f}) => f(...args));

// Project ref extraído de la URL
const PROJECT_REF = "mwfxxppefpyaxwtybcnf";
const SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13Znh4cHBlZnB5YXh3dHliY25mIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NjM3Mzk4MywiZXhwIjoyMDkxOTQ5OTgzfQ.Q4AWe3YtYHrY90QFASLNsEUPbk_-XWVOiI_N5nF1GxE";

const FULL_SQL = `
-- ============================================================
-- West House: Crear tablas académicas y columnas faltantes
-- ============================================================

-- 1. ASSIGNMENTS
CREATE TABLE IF NOT EXISTS public.assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT,
    title TEXT NOT NULL,
    description TEXT,
    due_date TIMESTAMP WITH TIME ZONE,
    created_by UUID,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);
ALTER TABLE public.assignments ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='assignments' AND policyname='assignments_all') THEN
    CREATE POLICY "assignments_all" ON public.assignments FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;

-- 2. ASSIGNMENT_SUBMISSIONS
CREATE TABLE IF NOT EXISTS public.assignment_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id BIGINT REFERENCES public.assignments(id) ON DELETE CASCADE,
    student_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    file_url TEXT NOT NULL,
    grade NUMERIC,
    comments TEXT,
    submitted_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);
ALTER TABLE public.assignment_submissions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='assignment_submissions' AND policyname='ass_sub_all') THEN
    CREATE POLICY "ass_sub_all" ON public.assignment_submissions FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;

-- 3. QUIZZES
CREATE TABLE IF NOT EXISTS public.quizzes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT,
    title TEXT NOT NULL,
    description TEXT,
    created_by UUID,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);
ALTER TABLE public.quizzes ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='quizzes' AND policyname='quizzes_all') THEN
    CREATE POLICY "quizzes_all" ON public.quizzes FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;

-- 4. QUIZ_QUESTIONS
CREATE TABLE IF NOT EXISTS public.quiz_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id BIGINT REFERENCES public.quizzes(id) ON DELETE CASCADE,
    question TEXT NOT NULL,
    options JSONB NOT NULL,
    correct_option INTEGER NOT NULL
);
ALTER TABLE public.quiz_questions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='quiz_questions' AND policyname='quiz_q_all') THEN
    CREATE POLICY "quiz_q_all" ON public.quiz_questions FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;

-- 5. QUIZ_RESULTS
CREATE TABLE IF NOT EXISTS public.quiz_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id BIGINT REFERENCES public.quizzes(id) ON DELETE CASCADE,
    student_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    score INTEGER NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);
ALTER TABLE public.quiz_results ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='quiz_results' AND policyname='quiz_r_all') THEN
    CREATE POLICY "quiz_r_all" ON public.quiz_results FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;

-- 6. REWARDS
CREATE TABLE IF NOT EXISTS public.rewards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    cost INTEGER NOT NULL DEFAULT 100,
    icon TEXT DEFAULT 'fa-solid fa-gift',
    category TEXT DEFAULT 'general',
    active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);
ALTER TABLE public.rewards ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='rewards' AND policyname='rewards_all') THEN
    CREATE POLICY "rewards_all" ON public.rewards FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;

-- 7. USER_REWARDS
CREATE TABLE IF NOT EXISTS public.user_rewards (
    id TEXT PRIMARY KEY,
    student_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    reward_id BIGINT REFERENCES public.rewards(id) ON DELETE CASCADE,
    date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL,
    status TEXT DEFAULT 'pending'
);
ALTER TABLE public.user_rewards ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='user_rewards' AND policyname='user_rewards_all') THEN
    CREATE POLICY "user_rewards_all" ON public.user_rewards FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;

-- 8. Add missing columns to users table (gamification)
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS xp INTEGER DEFAULT 0;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS spendable_xp INTEGER DEFAULT 0;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS streak INTEGER DEFAULT 0;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS last_login DATE;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS badges JSONB DEFAULT '[]';
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS level_num INTEGER DEFAULT 1;

-- 9. Fix logs table: ensure correct columns exist
ALTER TABLE public.logs ADD COLUMN IF NOT EXISTS table_name TEXT;
ALTER TABLE public.logs ADD COLUMN IF NOT EXISTS action TEXT;
ALTER TABLE public.logs ADD COLUMN IF NOT EXISTS details TEXT;
ALTER TABLE public.logs ADD COLUMN IF NOT EXISTS user_id UUID;

-- Done!
SELECT 'Migration completed successfully' as result;
`;

async function runSQL(sql) {
    const url = `https://api.supabase.com/v1/projects/${PROJECT_REF}/database/query`;
    
    let fetchFn;
    try {
        fetchFn = global.fetch || (await import('node-fetch')).default;
    } catch(e) {
        // use node-fetch from node_modules
        const nf = require('node-fetch');
        fetchFn = nf.default || nf;
    }

    const res = await fetchFn(url, {
        method: 'POST',
        headers: {
            'Authorization': `Bearer ${SERVICE_KEY}`,
            'Content-Type': 'application/json'
        },
        body: JSON.stringify({ query: sql })
    });
    
    const text = await res.text();
    console.log(`Status: ${res.status}`);
    try {
        const json = JSON.parse(text);
        console.log(JSON.stringify(json, null, 2));
    } catch {
        console.log(text);
    }
}

runSQL(FULL_SQL).catch(console.error);
