// Script para crear las tablas académicas faltantes en Supabase
// Usa el endpoint de SQL de la Management API
const https = require('https');

const SUPABASE_URL = "https://mwfxxppefpyaxwtybcnf.supabase.co";
const SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13Znh4cHBlZnB5YXh3dHliY25mIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NjM3Mzk4MywiZXhwIjoyMDkxOTQ5OTgzfQ.Q4AWe3YtYHrY90QFASLNsEUPbk_-XWVOiI_N5nF1GxE";

const { createClient } = require('@supabase/supabase-js');
const supabase = createClient(SUPABASE_URL, SERVICE_KEY);

// SQL statements to create tables one by one
const sqlStatements = [
    // assignments
    `CREATE TABLE IF NOT EXISTS public.assignments (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        course_id BIGINT,
        title TEXT NOT NULL,
        description TEXT,
        due_date TIMESTAMP WITH TIME ZONE,
        created_by UUID,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
    )`,
    
    `ALTER TABLE public.assignments ENABLE ROW LEVEL SECURITY`,
    `DROP POLICY IF EXISTS "assignments_select_all" ON public.assignments`,
    `CREATE POLICY "assignments_select_all" ON public.assignments FOR SELECT USING (true)`,
    `DROP POLICY IF EXISTS "assignments_insert_all" ON public.assignments`,
    `CREATE POLICY "assignments_insert_all" ON public.assignments FOR INSERT WITH CHECK (true)`,
    `DROP POLICY IF EXISTS "assignments_update_all" ON public.assignments`,
    `CREATE POLICY "assignments_update_all" ON public.assignments FOR UPDATE USING (true)`,
    `DROP POLICY IF EXISTS "assignments_delete_all" ON public.assignments`,
    `CREATE POLICY "assignments_delete_all" ON public.assignments FOR DELETE USING (true)`,

    // assignment_submissions
    `CREATE TABLE IF NOT EXISTS public.assignment_submissions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        assignment_id BIGINT,
        student_id UUID,
        file_url TEXT NOT NULL,
        grade NUMERIC,
        comments TEXT,
        submitted_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
    )`,
    
    `ALTER TABLE public.assignment_submissions ENABLE ROW LEVEL SECURITY`,
    `DROP POLICY IF EXISTS "ass_sub_select_all" ON public.assignment_submissions`,
    `CREATE POLICY "ass_sub_select_all" ON public.assignment_submissions FOR SELECT USING (true)`,
    `DROP POLICY IF EXISTS "ass_sub_insert_all" ON public.assignment_submissions`,
    `CREATE POLICY "ass_sub_insert_all" ON public.assignment_submissions FOR INSERT WITH CHECK (true)`,
    `DROP POLICY IF EXISTS "ass_sub_update_all" ON public.assignment_submissions`,
    `CREATE POLICY "ass_sub_update_all" ON public.assignment_submissions FOR UPDATE USING (true)`,
    `DROP POLICY IF EXISTS "ass_sub_delete_all" ON public.assignment_submissions`,
    `CREATE POLICY "ass_sub_delete_all" ON public.assignment_submissions FOR DELETE USING (true)`,

    // quizzes
    `CREATE TABLE IF NOT EXISTS public.quizzes (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        course_id BIGINT,
        title TEXT NOT NULL,
        description TEXT,
        created_by UUID,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
    )`,
    
    `ALTER TABLE public.quizzes ENABLE ROW LEVEL SECURITY`,
    `DROP POLICY IF EXISTS "quizzes_select_all" ON public.quizzes`,
    `CREATE POLICY "quizzes_select_all" ON public.quizzes FOR SELECT USING (true)`,
    `DROP POLICY IF EXISTS "quizzes_insert_all" ON public.quizzes`,
    `CREATE POLICY "quizzes_insert_all" ON public.quizzes FOR INSERT WITH CHECK (true)`,
    `DROP POLICY IF EXISTS "quizzes_update_all" ON public.quizzes`,
    `CREATE POLICY "quizzes_update_all" ON public.quizzes FOR UPDATE USING (true)`,
    `DROP POLICY IF EXISTS "quizzes_delete_all" ON public.quizzes`,
    `CREATE POLICY "quizzes_delete_all" ON public.quizzes FOR DELETE USING (true)`,

    // quiz_questions
    `CREATE TABLE IF NOT EXISTS public.quiz_questions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        quiz_id BIGINT,
        question TEXT NOT NULL,
        options JSONB NOT NULL,
        correct_option INTEGER NOT NULL
    )`,
    
    `ALTER TABLE public.quiz_questions ENABLE ROW LEVEL SECURITY`,
    `DROP POLICY IF EXISTS "quiz_q_select_all" ON public.quiz_questions`,
    `CREATE POLICY "quiz_q_select_all" ON public.quiz_questions FOR SELECT USING (true)`,
    `DROP POLICY IF EXISTS "quiz_q_insert_all" ON public.quiz_questions`,
    `CREATE POLICY "quiz_q_insert_all" ON public.quiz_questions FOR INSERT WITH CHECK (true)`,
    `DROP POLICY IF EXISTS "quiz_q_update_all" ON public.quiz_questions`,
    `CREATE POLICY "quiz_q_update_all" ON public.quiz_questions FOR UPDATE USING (true)`,
    `DROP POLICY IF EXISTS "quiz_q_delete_all" ON public.quiz_questions`,
    `CREATE POLICY "quiz_q_delete_all" ON public.quiz_questions FOR DELETE USING (true)`,

    // quiz_results
    `CREATE TABLE IF NOT EXISTS public.quiz_results (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        quiz_id BIGINT,
        student_id UUID,
        score INTEGER NOT NULL,
        completed_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
    )`,
    
    `ALTER TABLE public.quiz_results ENABLE ROW LEVEL SECURITY`,
    `DROP POLICY IF EXISTS "quiz_r_select_all" ON public.quiz_results`,
    `CREATE POLICY "quiz_r_select_all" ON public.quiz_results FOR SELECT USING (true)`,
    `DROP POLICY IF EXISTS "quiz_r_insert_all" ON public.quiz_results`,
    `CREATE POLICY "quiz_r_insert_all" ON public.quiz_results FOR INSERT WITH CHECK (true)`,
    `DROP POLICY IF EXISTS "quiz_r_update_all" ON public.quiz_results`,
    `CREATE POLICY "quiz_r_update_all" ON public.quiz_results FOR UPDATE USING (true)`,
    `DROP POLICY IF EXISTS "quiz_r_delete_all" ON public.quiz_results`,
    `CREATE POLICY "quiz_r_delete_all" ON public.quiz_results FOR DELETE USING (true)`,

    // rewards
    `CREATE TABLE IF NOT EXISTS public.rewards (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        description TEXT,
        cost INTEGER NOT NULL DEFAULT 100,
        icon TEXT DEFAULT 'fa-solid fa-gift',
        category TEXT DEFAULT 'general',
        active BOOLEAN DEFAULT true,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
    )`,

    `ALTER TABLE public.rewards ENABLE ROW LEVEL SECURITY`,
    `DROP POLICY IF EXISTS "rewards_select_all" ON public.rewards`,
    `CREATE POLICY "rewards_select_all" ON public.rewards FOR SELECT USING (true)`,
    `DROP POLICY IF EXISTS "rewards_insert_all" ON public.rewards`,
    `CREATE POLICY "rewards_insert_all" ON public.rewards FOR INSERT WITH CHECK (true)`,
    `DROP POLICY IF EXISTS "rewards_update_all" ON public.rewards`,
    `CREATE POLICY "rewards_update_all" ON public.rewards FOR UPDATE USING (true)`,
    `DROP POLICY IF EXISTS "rewards_delete_all" ON public.rewards`,
    `CREATE POLICY "rewards_delete_all" ON public.rewards FOR DELETE USING (true)`,

    // user_rewards
    `CREATE TABLE IF NOT EXISTS public.user_rewards (
        id TEXT PRIMARY KEY,
        student_id UUID,
        reward_id BIGINT,
        date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
        status TEXT DEFAULT 'pending'
    )`,
    
    `ALTER TABLE public.user_rewards ENABLE ROW LEVEL SECURITY`,
    `DROP POLICY IF EXISTS "user_rewards_select_all" ON public.user_rewards`,
    `CREATE POLICY "user_rewards_select_all" ON public.user_rewards FOR SELECT USING (true)`,
    `DROP POLICY IF EXISTS "user_rewards_insert_all" ON public.user_rewards`,
    `CREATE POLICY "user_rewards_insert_all" ON public.user_rewards FOR INSERT WITH CHECK (true)`,
    `DROP POLICY IF EXISTS "user_rewards_update_all" ON public.user_rewards`,
    `CREATE POLICY "user_rewards_update_all" ON public.user_rewards FOR UPDATE USING (true)`,
    `DROP POLICY IF EXISTS "user_rewards_delete_all" ON public.user_rewards`,
    `CREATE POLICY "user_rewards_delete_all" ON public.user_rewards FOR DELETE USING (true)`,

    // Add missing columns to users table
    `ALTER TABLE public.users ADD COLUMN IF NOT EXISTS xp INTEGER DEFAULT 0`,
    `ALTER TABLE public.users ADD COLUMN IF NOT EXISTS spendable_xp INTEGER DEFAULT 0`,
    `ALTER TABLE public.users ADD COLUMN IF NOT EXISTS streak INTEGER DEFAULT 0`,
    `ALTER TABLE public.users ADD COLUMN IF NOT EXISTS last_login DATE`,
    `ALTER TABLE public.users ADD COLUMN IF NOT EXISTS badges JSONB DEFAULT '[]'`,
];

async function executeSQL(sql) {
    const response = await fetch(`${SUPABASE_URL}/rest/v1/rpc/`, {
        method: 'POST',
        headers: {
            'apikey': SERVICE_KEY,
            'Authorization': `Bearer ${SERVICE_KEY}`,
            'Content-Type': 'application/json'
        }
    });
}

async function runAll() {
    console.log('🚀 Iniciando creación de tablas académicas en Supabase...\n');
    
    for (const sql of sqlStatements) {
        const shortSql = sql.trim().substring(0, 70).replace(/\s+/g, ' ');
        try {
            const response = await fetch(`${SUPABASE_URL}/rest/v1/`, {
                method: 'POST',
                headers: {
                    'apikey': SERVICE_KEY,
                    'Authorization': `Bearer ${SERVICE_KEY}`,
                    'Content-Type': 'application/json',
                    'Prefer': 'return=minimal'
                }
            });
        } catch(e) {}
        
        // Use supabase rpc if available, otherwise try direct
        try {
            const { error } = await supabase.rpc('exec_sql', { sql_query: sql });
            if (error && !error.message.includes('already exists') && !error.message.includes('Could not find')) {
                console.log(`⚠️  ${shortSql}...\n   ↳ ${error.message}`);
            } else {
                console.log(`✅ ${shortSql}...`);
            }
        } catch(err) {
            console.log(`❌ Error en: ${shortSql}...\n   ↳ ${err.message}`);
        }
    }

    // Now verify by trying to insert/select
    console.log('\n🔍 Verificando tablas creadas...');
    const tables = ['assignments', 'assignment_submissions', 'quizzes', 'quiz_questions', 'quiz_results', 'rewards', 'user_rewards'];
    for (const t of tables) {
        const { data, error } = await supabase.from(t).select('*').limit(1);
        if (error) {
            console.log(`❌ ${t}: ${error.message}`);
        } else {
            console.log(`✅ ${t}: OK`);
        }
    }
}

runAll().catch(console.error);
